In [5]:
import pandas as pd
import json
import re
# First, import the required libraries. You will need the pandas library to work with data frames and the nltk library to tokenize the sentences and words in the transcripts column.
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
nltk.download('punkt')

! cp /content/drive/MyDrive/QU-DFKI-Thesis-ASR/Experimentation/data/results.json   /content/results.json

#@title ###**To count the number of occurrences of each word over the sentences located in the transcripts column of a data frame:**

###########################################################################################################################################################
########### creat a Dataframe called "dataset_audiofilename_transcript_accent" contains all audiofilename and thier 'transcript' and 'test_file' /Accent####
###########################################################################################################################################################
list_dataset_test_=['test_at.txt','test_gb.txt','test_it.txt','test_de_al.txt','test_fr.txt','test_de_ni.txt','test_ch.txt',
               'test_de.txt','test_us.txt','test_ca.txt','test_ru.txt']
list_dataset_test_accent=['Österreichisches Deutsch','Britisches Deutsch','Italienisch Deutsch','Alemannische Färbung,Schweizer Standart Deutsch',
'Französisch Deutsch','Niederländisch Deutsch','Schweizerdeutsch','Deutschland Deutsch','Amerikanisches Deutsch','Kanadisches Deutsch','Russisch Deutsch']

data_dict_accent_duration  = dict(zip( list_dataset_test_, list_dataset_test_accent))  

# create an empty set to store the words that meet all 11 accents


accent_long_list=[]
 

### here is the required_word
# required_word="Start"
# required_word=input('Insert a word to test it please? ')
newfile=0


### here is the required_word
required_word="ich"
newfile=0
# dict_audiofilename_transcript_accent=[]
# To find out the Audio file's Accent
list_test_accent_txt_values=[]
list_test_accent_txt_keys=[]
list_test_file=[]
list_accent_long=[]

if __name__ == "__main__":
  Dict_results = json.load(open('results.json'))
  for test_file in Dict_results:
    # print(test_file)
    list_test_accent_txt_values_temp = [v["reference"] for v in Dict_results[test_file].values()]
    list_test_accent_txt_keys_temp=[re.split(r'[.|/]',k)[9] for k in Dict_results[test_file].keys()]
    list_test_file_temp=[test_file for v in Dict_results[test_file].values()]

# creat a Dataframe called  dataset_audiofilename_transcript_accent contains all audiofilename and thier 'transcript' and 'test_file' /Accent
    list_test_accent_txt_values.extend(list_test_accent_txt_values_temp)
    list_test_accent_txt_keys.extend(list_test_accent_txt_keys_temp)
    list_test_file.extend(list_test_file_temp)
    keys=['audiofilename','transcript','test_file']
    trans_dict_test_file_result = dict(zip(keys,[list_test_accent_txt_keys, list_test_accent_txt_values,list_test_file]))
    
dataset_audiofilename_transcript_accent = pd.DataFrame(trans_dict_test_file_result)
 
# Tokenize the sentences in the transcripts column using the sent_tokenize function from the nltk library. This will create a list of sentences.
sentences = dataset_audiofilename_transcript_accent['transcript'].apply(sent_tokenize)

# Tokenize the words in each sentence using the word_tokenize function from the nltk library. This will create a list of words for each sentence.
words = sentences.apply(lambda x: [word_tokenize(sentence) for sentence in x])

# Flatten the list of words so that you have a single list of all words in the transcripts column.
all_words = [word for sentence in words for word_list in sentence for word in word_list]

# Use the Counter function from the collections library to count the occurrences of each word.
from collections import Counter
word_counts = Counter(all_words)

# Convert the word_counts object to a data frame using the pd.DataFrame function.
word_counts_dataset_audiofilename_transcript_accent = pd.DataFrame.from_dict(word_counts, orient='index', columns=['count'])

# Sort the data frame by the count column in descending order.
word_counts_dataset_audiofilename_transcript_accent = word_counts_dataset_audiofilename_transcript_accent.sort_values('count', ascending=False)

print('Count the number of occurrences of each word over the sentences located in the transcripts column of a data frame:')
print(word_counts_dataset_audiofilename_transcript_accent)
word_counts_dataset_audiofilename_transcript_accent.to_csv('number_of_occurrences_of_each_word.csv', index=True)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Count the number of occurrences of each word over the sentences located in the transcripts column of a data frame:
               count
die            14029
der            13302
ist             7629
und             7554
in              7195
...              ...
kunstdünger        1
hovan              1
rocky              1
inbesitznahme      1
kippe              1

[54083 rows x 1 columns]

In [9]:
word_counts_dataset_audiofilename_transcript_accent

               count
die            14029
der            13302
ist             7629
und             7554
in              7195
...              ...
kunstdünger        1
hovan              1
rocky              1
inbesitznahme      1
kippe              1

[54083 rows x 1 columns]

In [7]:
import pandas as pd

# create a sample DataFrame
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
        'age': [25, 32, 18, 47],
        'gender': ['F', 'M', 'M', 'M']}
df = pd.DataFrame(data)

# save the DataFrame to a CSV file with the index
df.to_csv('my_dataframe.csv', index=True)